; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Tue Nov 19 2019 22:40:08 GMT+0000 (Hora padrão da Europa Ocidental)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


