; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Tue Nov 19 2019 22:40:08 GMT+0000 (Hora padrão da Europa Ocidental)

