; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Tue Nov 19 2019 22:40:08 GMT+0000 (Hora padrão da Europa Ocidental)
; Wait for set temperatures to be reached
M116 P0

